export const permissionsSeed=[

  "PROJECT_CREATE",
  "PROJECT_READ",
  "PROJECT_UPDATE",
  "PROJECT_DELETE",

  "TASK_CREATE",
  "TASK_READ",
  "TASK_UPDATE",
  "TASK_DELETE",

  "WORKFLOW_READ",
  "WORKFLOW_UPDATE",

  "MASTER_DATA_READ",
  "MASTER_DATA_UPDATE",

  "USER_CREATE",
  "USER_READ",
  "USER_UPDATE",
  "USER_DELETE",

  "COMMENT_READ",
  "COMMENT_CREATE",
  "COMMENT_UPDATE",
  "COMMENT_DELETE",
  "COMMENT_DELETE_ANY",

  "ACTIVITY_LOG_READ",
  "ACTIVITY_LOG_CREATE",
  "ACTIVITY_LOG_READ_ANY",
  "ACTIVITY_LOG_DELETE",
  "ACTIVITY_TYPE_MANAGE"

]