export const rolePermissionsSeed = {

  ADMIN: [
    "PROJECT_CREATE",
    "PROJECT_READ",
    "PROJECT_UPDATE",
    "PROJECT_DELETE",

    "TASK_CREATE",
    "TASK_READ",
    "TASK_UPDATE",
    "TASK_DELETE",

    "WORKFLOW_READ",
    "WORKFLOW_UPDATE",

    "MASTER_DATA_READ",
    "MASTER_DATA_UPDATE",

    "USER_CREATE",
    "USER_READ",
    "USER_UPDATE",
    "USER_DELETE",

    "COMMENT_CREATE",
    "COMMENT_READ",
    "COMMENT_UPDATE",
    "COMMENT_DELETE",
    "COMMENT_DELETE_ANY",
  ],

  GERENCIA: [
    "PROJECT_CREATE",
    "PROJECT_READ",
    "PROJECT_UPDATE",
    "PROJECT_DELETE",

    "TASK_CREATE",
    "TASK_READ",
    "TASK_UPDATE",
    "TASK_DELETE",

    "WORKFLOW_READ",
    "WORKFLOW_UPDATE",

    "MASTER_DATA_READ",

    "USER_READ",

    "COMMENT_CREATE",
    "COMMENT_READ",
    "COMMENT_UPDATE",
    "COMMENT_DELETE",
  ],

  PROJECT_MANAGER: [
    "PROJECT_CREATE",
    "PROJECT_READ",
    "PROJECT_UPDATE",

    "TASK_CREATE",
    "TASK_READ",
    "TASK_UPDATE",

    "WORKFLOW_READ",
    "WORKFLOW_UPDATE",

    "MASTER_DATA_READ",

    "USER_READ",

    "COMMENT_CREATE",
    "COMMENT_READ",
    "COMMENT_UPDATE",
    "COMMENT_DELETE",
  ],

  SUPERVISOR: [
    "PROJECT_READ",

    "TASK_READ",
    "TASK_UPDATE",

    "WORKFLOW_READ",
    "WORKFLOW_UPDATE",

    "MASTER_DATA_READ",

    "USER_READ",

    "COMMENT_CREATE",
    "COMMENT_READ",
    "COMMENT_UPDATE",
    "COMMENT_DELETE",
  ],

  OPERARIO: [
    "PROJECT_READ",

    "TASK_READ",

    "WORKFLOW_READ",
    "WORKFLOW_UPDATE",

    "MASTER_DATA_READ",

    "USER_READ",

    "COMMENT_CREATE",
    "COMMENT_READ",
    "COMMENT_UPDATE",
    "COMMENT_DELETE",
  ],

} as const